/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Sanjeewa Kulathunga
 */
public class Mediadescription extends javax.swing.JFrame {

    /**
     * Creates new form Mediadescription
     */
    public Mediadescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        MediaIcon = new javax.swing.JLabel();
        MediaTitle = new javax.swing.JLabel();
        MediaAuthor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();
        MediaDescription = new javax.swing.JLabel();
        btnBorrow = new javax.swing.JButton();
        MediaName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MediaID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jButton6.setBackground(new java.awt.Color(74, 137, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(750, 10, 40, 40);

        MediaIcon.setBackground(new java.awt.Color(255, 255, 0));
        MediaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MediaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/1003.jpg"))); // NOI18N
        MediaIcon.setOpaque(true);
        jPanel1.add(MediaIcon);
        MediaIcon.setBounds(40, 150, 270, 410);

        MediaTitle.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        MediaTitle.setForeground(new java.awt.Color(255, 255, 255));
        MediaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MediaTitle.setText("Media Description");
        jPanel1.add(MediaTitle);
        MediaTitle.setBounds(60, 60, 690, 34);

        MediaAuthor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MediaAuthor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MediaAuthor.setText("Author");
        MediaAuthor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(MediaAuthor);
        MediaAuthor.setBounds(430, 230, 340, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Author: ");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 230, 90, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Description:");
        jLabel8.setToolTipText("");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 310, 100, 40);

        lblAvailable.setBackground(new java.awt.Color(255, 255, 0));
        lblAvailable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAvailable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvailable.setOpaque(true);
        jPanel1.add(lblAvailable);
        lblAvailable.setBounds(40, 120, 270, 30);

        MediaDescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MediaDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MediaDescription.setText("Author");
        MediaDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(MediaDescription);
        MediaDescription.setBounds(430, 310, 340, 170);

        btnBorrow.setBackground(java.awt.Color.green);
        btnBorrow.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBorrow.setText("Borrow");
        jPanel1.add(btnBorrow);
        btnBorrow.setBounds(330, 500, 440, 50);

        MediaName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MediaName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MediaName.setText("Name");
        MediaName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(MediaName);
        MediaName.setBounds(430, 150, 340, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Name :");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 150, 90, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        MediaID.setText("jLabel1");
        jPanel1.add(MediaID);
        MediaID.setBounds(0, 580, 51, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed
    public void addBorrowListener(ActionListener listnerforbutton){
        btnBorrow.addActionListener(listnerforbutton);
    }

    public JLabel getLblAvailable() {
        return lblAvailable;
    }
    
    public JLabel getMediaAuthor() {
        return MediaAuthor;
    }

    public JLabel getMediaID() {
        return MediaID;
    }
    
    public JLabel getMediaDescription() {
        return MediaDescription;
    }

    public JLabel getMediaIcon() {
        return MediaIcon;
    }

    public JLabel getMediaName() {
        return MediaName;
    }

    public JLabel getMediaTitle() {
        return MediaTitle;
    }

    public JButton getBtnBorrow() {
        return btnBorrow;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MediaAuthor;
    private javax.swing.JLabel MediaDescription;
    private javax.swing.JLabel MediaID;
    private javax.swing.JLabel MediaIcon;
    private javax.swing.JLabel MediaName;
    private javax.swing.JLabel MediaTitle;
    private javax.swing.JButton btnBorrow;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvailable;
    // End of variables declaration//GEN-END:variables
}
