/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Muhammad Adil FAYYAZ
 */
public class SignupForm extends javax.swing.JFrame {

    /**
     * Creates new form SignupForm
     */
    public SignupForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserFName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        txtUserLName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        txtUserPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        txtUserFName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(txtUserFName);
        txtUserFName.setBounds(100, 190, 620, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 160, 200, 25);

        btnSignup.setBackground(new java.awt.Color(0, 255, 0));
        btnSignup.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSignup.setText("Signup");
        jPanel1.add(btnSignup);
        btnSignup.setBounds(100, 530, 620, 50);

        txtUserLName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(txtUserLName);
        txtUserLName.setBounds(100, 280, 620, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 250, 200, 25);

        txtUserEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(txtUserEmail);
        txtUserEmail.setBounds(100, 370, 620, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 430, 200, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 340, 200, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Signup.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 70, 630, 70);

        back.setBackground(new java.awt.Color(0, 255, 0));
        back.setText("<< Back");
        jPanel1.add(back);
        back.setBounds(20, 10, 100, 29);

        txtUserPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(txtUserPassword);
        txtUserPassword.setBounds(100, 460, 620, 40);

        jButton2.setBackground(new java.awt.Color(74, 137, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(750, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void DisplayInfo(String info){
        JOptionPane.showMessageDialog(this,info,"Alert",JOptionPane.INFORMATION_MESSAGE);
    }
    public void DisplayError(String error){
        JOptionPane.showMessageDialog(this,error,"Alert",JOptionPane.WARNING_MESSAGE);
    }
    public void addSignupListener(ActionListener listnerforbutton){
        btnSignup.addActionListener(listnerforbutton);
    }
    public void addBackListener(ActionListener listnerforbutton){
        back.addActionListener(listnerforbutton);
    }
    /**
     * @param args the command line arguments
     */

    public JButton getBtnSignup() {
        return btnSignup;
    }

    public void setBtnSignup(JButton btnSignup) {
        this.btnSignup = btnSignup;
    }

    public JTextField getTxtUserEmail() {
        return txtUserEmail;
    }

    public void setTxtUserEmail(JTextField txtUserEmail) {
        this.txtUserEmail = txtUserEmail;
    }

    public JTextField getTxtUserFName() {
        return txtUserFName;
    }

    public void setTxtUserFName(JTextField txtUserFName) {
        this.txtUserFName = txtUserFName;
    }

    public JTextField getTxtUserLName() {
        return txtUserLName;
    }

    public void setTxtUserLName(JTextField txtUserLName) {
        this.txtUserLName = txtUserLName;
    }

    public JPasswordField getTxtUserPassword() {
        return txtUserPassword;
    }

    public void setTxtUserPassword(JPasswordField txtUserPassword) {
        this.txtUserPassword = txtUserPassword;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserFName;
    private javax.swing.JTextField txtUserLName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
